name: Build

on:
  push:
    branches:
      - main

jobs:
  windows-x86_64:
    name: windows x86_64
    runs-on: windows-latest
    env:
      build_package_name: veil-wallet win-x86_64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: |
          flutter config --no-analytics
          flutter config --enable-windows-desktop
          flutter pub get
      - name: Build executable
        run: flutter build windows --release
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.build_package_name }}
          path: build/windows/runner/Release/

  linux-x86_64:
    name: linux x86_64
    runs-on: ubuntu-latest
    env:
      build_package_name: veil-wallet linux-x86_64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install libsecret-1-dev clang pkg-config ninja-build libgtk-3-dev cmake
          flutter config --no-analytics
          flutter config --enable-linux-desktop
          flutter pub get
      - name: Build executable
        run: flutter build linux --release
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.build_package_name }}
          path: 'build/linux/x64/release/bundle/'

  osx-x64:
    name: osx x86_64
    runs-on: macos-latest
    env:
      build_package_name: veil-wallet osx-x86_64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
          cache: false
      - name: Install dependencies
        run: |
          flutter config --no-analytics
          flutter config --enable-macos-desktop          
          flutter pub cache clean
          flutter pub get
      - name: Build executable
        run: |
          flutter clean
          flutter build macos
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.build_package_name }}
          path: build/macos/Build/Products/Release/veil_wallet.app

  ios:
    name: ios
    runs-on: macos-latest
    env:
      build_package_name: veil-wallet ios
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
      - name: Install dependencies
        run: |
          flutter config --no-analytics
          flutter pub get
      - name: Build executable
        run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.build_package_name }}
          path: build/ios/iphoneos

  android:
    name: android
    runs-on: ubuntu-latest
    env:
      build_package_name: veil-wallet android
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: dtolnay/rust-toolchain@stable
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
      - name: Install dependencies
        run: |
          flutter config --no-analytics
          flutter pub get
      - name: Build executable
        run: flutter build apk --release
      - name: Sign executable
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.build_package_name }}
          path: build/android/iphoneos